### PR TITLE
fix: update hooks for webpack 5

### PR DESCRIPTION
**Pull request by bertho-zero**
Related to https://github.com/gregberge/loadable-components/issues/636

### CODE REVIEW

**Comment by duterte** [comment]
any information why this pull request was declined ?

**Comment by theKashey** [comment]
It wasn't?

**Comment by duterte** [comment]
I have my own created version to fix this Issue can I submit a pull request too ?

**Comment by joacub** [comment]
what about this ?

**Comment by theKashey** [comment]
testing....

**Comment by theKashey** [comment]
Working perfectly. That's everyone for making this happen (and sorry for being 🐢 )

#689 has to be addressed before releasing a new version...

**Pull request merged**
