### PR TITLE
fix: loadAsync resolve

### PR DESCRIPTION
**Pull request by jinasonlin**
## Summary

I think loadAsync should like loadSync resolve module and copy Component statics (hoistNonReactStatics).

In some cases, I hope loadable can trigger load end, so add onLoad in options.

### CODE REVIEW

**Comment by theKashey** [comment]
- I can approve your first change, as it's a bug fix
- I __can not__ approve your second change, as it lacking: tests, documentation, an update to typescript definitions. Unfortunately, you cannot "just add" a new field to the option, especially as a part of another change.

**Comment by jinasonlin** [comment]
Okay, I'll split the PR.  Please review the fix.

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
https://github.com/gregberge/loadable-components/releases/tag/v5.15.2

**Pull request merged**
