### PR TITLE
Fix Webpack 5 contenthash bug in LoadablePlugin

### PR DESCRIPTION
**Pull request by sumanbh**
Fixes https://github.com/gregberge/loadable-components/issues/712

### CODE REVIEW

**Comment by pauliusuza** [comment]
would it be possible to release this? 
we have an issue with production build which this fixes

**Comment by theKashey** [comment]
Oh. It still hasnt 🤯 
Sorry, my bad.

**Comment by pauliusuza** [comment]
> Oh. It still hasnt 🤯
> Sorry, my bad.

@theKashey yes it would be great to have this released soon if possible, thanks so much

**Comment by theKashey** [comment]
All packages have been updated to v5.15.0

**Pull request merged**
